name: Mfuns_auto_sign
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 23 * * *'
env:
    Account: ${{ secrets.ACCOUNT }}
    Password: ${{ secrets.PASSWORD }}
    Feishu_bot_secret: ${{ secrets.FEISHU_BOT_SECRET }}
    Feishu_webhook: ${{ secrets.FEISHU_WEBHOOK }}

jobs:
  auto_sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.16'
      - run: pip install tzdata
      - run: pip install requests
      - run: python sign_action.py
      
